// everforrest colorscheme
[dark]
foreground = "#D3C6AA"
red = "#E67E80"
yellow = "#DBBC7F"
green = "#A7C080"
blue = "#7FBBB3"
purple = "#D699B6"
aqua = "#83C092"
orange = "#E69875"
statusline_1 = "#A7C080"
statusline_2 = "#D3C6AA"
statusline_3 = "#E67E80"
grey_0 = "#7A8478"
grey_1 = "#859289"
grey_2 = "#9DA9A0"
background_dim = "#1E2326"
background_0 = "#272E33"
background_1 = "#2E383C"
background_2 = "#374145"
background_3 = "#414B50"
background_4 = "#495156"
background_5 = "#4F5B58"
background_red = "#493B40"
background_yellow = "#45443C"
background_green = "#3C4841"
background_blue = "#384B55"
background_purple = "#463F48"
background_visual = "#4C3743"

[light]
foreground = "#5C6A72"
red = "#F85552"
yellow = "#DFA000"
green = "#8DA101"
blue = "#3A94C5"
purple = "#DF69BA"
aqua = "#35A77C"
orange = "#F57D26"
statusline_1 = "#93B259"
statusline_2 = "#708089"
statusline_3 = "#E66868"
grey_0 = "#A6B0A0"
grey_1 = "#939F91"
grey_2 = "#829181"
background_dim = "#F2EFDF"
background_0 = "#FFFBEF"
background_1 = "#F8F5E4"
background_2 = "#F2EFDF"
background_3 = "#EDEADA"
background_4 = "#E8E5D5"
background_5 = "#BEC5B2"
background_red = "#FFE7DE"
background_yellow = "#FEF2D5"
background_green = "#F3F5D9"
background_blue = "#ECF5ED"
background_purple = "#FCECED"
background_visual = "#F0F2D4"